name: CI workflow

on: [push, pull_request]

defaults:
  run:
    working-directory: RoundupFunction

concurrency:
  group: gh-ci-ref-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and test application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and test with Maven
        run: ./mvnw -DskipTests package
